<?php
$z[0]=Array("global","",36,68);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",2760,2792);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",2815,2841);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",2952,2984);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",3053,3085);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",3153,3185);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",3298,3330);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("channel","\r\n            <li><a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a></li>\r\n            ",3496,3751);
$z[7][4]['type']="top";
$z[7][4]['row']="10";
$z[7][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[8]=Array("global","",3830,3862);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("channelartlist","\r\n        <ul id=\"dropmenu{dede:field.typeid/}\" class=\"dropMenu\">\r\n          {dede:channel type='son' noself='yes'}\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n          {/dede:channel}\r\n        </ul>\r\n        ",3899,4217);
$z[9][4]['typeid']="top";
$z[9][4]['cacheid']="channelsonlist";
$z[10]=Array("arclist","\r\n          <li>[field:image/]</li>\r\n          ",4487,4629);
$z[10][4]['typeid']="28";
$z[10][4]['row']="10";
$z[10][4]['orderby']="id";
$z[10][4]['imgwidth']="1000";
$z[10][4]['imgheight']="341";

?>