<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",486,518);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("include","",633,668);
$z[5][4]['filename']="head.htm";
$z[6]=Array("field","",818,847);
$z[6][4]['name']="position";
$z[7]=Array("channel"," <a class=\"pic_menu_ii\" href='[field:typeurl/]'>[field:typename/]</a> ",933,1127);
$z[7][4]['type']="son";
$z[7][4]['currentstyle']="<a href='~typelink~' class='thisclass2 pic_menu_ii'>~typename~</a>";
$z[8]=Array("list","\r\n          <li>\r\n            <p><a href=\"[field:arcurl/]\" class=\"pic\"><img src=\"[field:picname/]\" alt=\"[field:title/]\"/></a></p>\r\n            <p class=\"pic_text\">[field:title/]</p>\r\n          </li>\r\n          ",1224,1471);
$z[8][4]['pagesize']="12";
$z[9]=Array("pagelist","",1610,1688);
$z[9][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[9][4]['listsize']="5";
$z[10]=Array("include","",1832,1869);
$z[10][4]['filename']="footer.htm";

?>